sudo: required

services:
  - docker

before_install:
  - docker build . -t builder-image --target=builder
  - docker run -it builder-image mvn test
install:
  - docker build . -t finalimagename:latest
scripts:
  - /bin/bash -c "echo \"This is supposed to be a deploy step\""